name: CI — Verificar pruebas tras merge a develop (Python)

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  contents: read

jobs:
  verify-tests-on-develop:
    name: Verificar pruebas (merge a develop)
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Si usas extras: if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run tests (pytest)
        run: |
          pytest -q
